# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionPath: ./

jobs:
- job: 
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: SonarCloudPrepare@1
    displayName: Prepare Sonarcloud analysis
    inputs:
      SonarCloud: 'sonarcloud-RedNarwhal'
      organization: '2006-jun15-net'
      scannerMode: 'MSBuild'
      projectKey: '2006-jun15-net_josh-project1'
      projectName: 'Josh Project 1'
      projectVersion: '0.5'

  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'

  - task: SonarCloudAnalyze@1
    displayName: Run Sonarcloud analysis

  - task: SonarCloudPublish@1
    displayName: Publish Sonarcloud result
    inputs:
      pollingTimeoutSec: '300'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      codeCoverageEnabled: true
      testRunTitle: 'windows'
      platform: 'Any CPU'
      configuration: 'Release'

  

  - script: dotnet publish -c Release -o ../publish
    displayName: dotnet publish
    workingDirectory: $(solutionPath)

  # - task: AzureRmWebAppDeployment@4
  #   inputs:
  #     ConnectionType: 'AzureRM'
  #     azureSubscription: 'Azure subscription 1(e8660cf1-4aa2-42f9-a6c8-6ded191f7438)'
  #     appType: 'webApp'
  #     WebAppName: 'bertrand-proj1'
  #     packageForLinux: '$(System.DefaultWorkingDirectory)/publish'
